### ISSUE TITLE
working with git

### ISSUE THREAD

**Issue by joelgeorgem** [jp-praveen/Rendezvous#1]
I have transferred the code to a .m file.

Modify that and add new files whenever needed.

Now onwards, work with a local copy of this repository.

Do a push whenever you have made some progress.

**Comment by jp-praveen** [comment]
Sir, I created a new branch and started coding on that and didn't use the master branch. Whenever I make changes, only the pull option comes and I can't see any push option. How do I use the push?

**Comment by jp-praveen** [comment]
Sir, I have a doubt about finding the tmin. Our aim is to Rendezvous at target orbit at t=time period/4 of the targets orbit. Initially, both target and chaser are at their respective perigee and then using transfer time as ‘t’ we find the delta V. Then we try to find whether there exist any time ‘tnew’ with a lesser delta V by waiting for some time in chasers orbit. But, Isn’t the transfer time always be equal to time ‘t’, because if we find any other ‘tnew’ as transfer time which is less than ‘t’, then the chaser will reach the destination point before the target as the target will reach the destination point only at t=time period/4. Kindly please clarify this doubt.

I wrote one code by taking the target initial position at perigee and varied the chasers initial position by 10degree anomaly from perigee iteratively. Then for different initial chasers position, I calculated the delta V for rendezvous to happen at t=T/4, and found delta V is lower at some true anomaly ranges.

**Comment by joelgeorgem** [comment]
The algorithm:
```
t = t_wait; dV = inf
while dV > dVmax
    t = t + dt
    compute dV for rendezvous at t (rendezvous point will be the location of the target at time t, and initial point will be the location of the chaser at time t_wait)
    if dV<dVmax
        ​exit loop
end
```
t is the tmin for given dVmax.

Now plot tmin as a function of t_wait.
