### ISSUE TITLE
orbit parameters

### ISSUE THREAD

**Issue by joelgeorgem** [jp-praveen/Rendezvous#13]
In the function `orbitparameters`, while computing true anomaly, you should be using `atan` and not `atand`.

Also, use `pi` and not `3.14`.

**Comment by jp-praveen** [comment]
Yes sir. Changed that

**Comment by joelgeorgem** [comment]
There seems to be something wrong with the perigee computation.

If we use r2 instead of r1 to compute it, then we get a different answer.

**Comment by jp-praveen** [comment]
Yes Sir. I was actually checking each parameter in the code by separately picking them up. I plotted the function used in Prussings method, 'F(1)=(sqrt((a_t^3)/u)*(4*pi+(alpha-sin(alpha))-(beta-sin(beta)))-dt)', by fixing dt and varying a to get 'a vs F' graph. I checked this graph for different initial r1 and r2 values. I found that this function has two roots, one complex and one real one. I have attached one such graph. 
![function](https://user-images.githubusercontent.com/55296086/65988012-a6758580-e4a4-11e9-9422-497d9732e9eb.jpg)
The 1st root(leftmost) is the complex one and the second one is the real one. The function becomes a complex one somewhere in between these 2 roots. While using fzero, if we give the initial value somewhere in between the two roots, the fzero while attempting to find an interval containing sign change, encounters a complex function value and terminates. But if we give the initial condition to be far-right it finds the real root. Earlier for even a little change in initial conditions, we got different outputs using fsolve. I think this is because the function actually takes some values of the order 10^-4 over a range of a. Since Fsolve is not a much precise method, the output varied each time we slightly changed the input.

Similarly for the book methods function,'F(1) = ((y/C)^1.5)*S+A*(y^0.5)-(u^0.5)'; y,C,S,A are functions of z, the z value sometimes has two roots, one z<0 (hyperbolic orbit) and another for z>0 (elliptic orbit). Previously we gave initial z to be 0. But sometimes the fzero finds the hyperbolic trajectory root. So we should change the initial value to be more positive like 30.

Then I found one more example case online with solution. The book method gave the exact answer, while the prussings method gave the correct value of 'a' and 'e'. The problem I think is in the value of the calculated Eccentric anomaly, which then affects the True anomaly, which further affects the perigee value. I checked the formulas but they are the same as that given in the paper. I will try looking into other ways of finding the mean anomaly.
